title: macOS Setup
description: Reference notes I wrote to myself. If you are a dev setting up a new Mac, they may be useful for you too.

author:
  name: lucasrla
  github: lucasrla

# pinning the version to v0.3.1
# v0.3.2 introduced issues with Liquid `sort` in `_includes/nav.html`
remote_theme: pmarsceill/just-the-docs@v0.3.1
color_scheme: "dark"
search_enabled: true

exclude: ["README.md", "TODOs.md", "vendor.noindex/", "bin/"]
# https://help.github.com/articles/migrating-your-pages-site-from-maruku
# markdown: GFM
