title: macOS Setup
description: Reference notes I wrote to myself. If you are a dev setting up a new Mac, they may be useful for you too.

author:
  name: lucasrla
  github: lucasrla

# https://github.com/pages-themes/minimal
# theme: jekyll-theme-minimal

remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true

exclude: ["README.md", "TODOs.md", "vendor.noindex/", "bin/"]
# https://help.github.com/articles/migrating-your-pages-site-from-maruku
# markdown: GFM
